# mkdocs.yml
site_name: "EERILY"
site_author: L Ma
site_description: "timE sERIes pLaYground (EERILY) is a playground for time series"
site_url: "https://emptymalei.github.io/eerily"
repo_url: "https://github.com/emptymalei/eerily"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/eerily"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo_transparent.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
      watch:
        - docs
  - mkdocs-jupyter:
      execute: True
      allow_errors: false


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Home": index.md
  - "Tutorials":
    - "Introduction": tutorials/index.md
    - "Generator Utilities": tutorials/generators_utils.py
    - "Generator Stepper": tutorials/generators_stepper.py
    - "Combining Multiple Steppers": tutorials/generators_stepper_operations.py
    - "Generator with Covariates": tutorials/generators_with_covariates.py
  - References:
    - "Introduction": references/index.md
    - "Data Generators":
        - references/generators/index.md
        - "generators.utils":
          - "generators.utils.base": references/generators/utils/base.md
          - "generators.utils.stepper": references/generators/utils/stepper.md
          - "generators.utils.noises": references/generators/utils/noises.md
          - "generators.utils.events": references/generators/utils/events.md
          - "generators.utils.choices": references/generators/utils/choices.md
          - "generators.utils.factory": references/generators/utils/factory.md
        - "generators.var": references/generators/var.md
        - "generators.spiking": references/generators/spiking.md
        - "generators.brownian": references/generators/brownian.md
        - "generators.elasticity": references/generators/elasticity.md
  - "Changelog": changelog.md
