# mkdocs.yml
site_name: "TESSA"
site_author: L Ma
site_description: "TimE SerieS plAygroun (TESSA) is a playground for time series"
site_url: "https://emptymalei.github.io/tessa"
repo_url: "https://github.com/emptymalei/tessa"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/tessa"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo_transparent.png



markdown_extensions:
  - admonition
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings

nav:
  - "Home": index.md
  - References:
    - "Introduction": references/index.md
    - "Data":
      - "data.generators":
        - references/data/generators/index.md
        - "data.generators.stepper": references/data/generators/stepper.md
        - "data.generators.elasticity": references/data/generators/elasticity.md
  - "Changelog": changelog.md
