# mkdocs.yml
site_name: "EERILY"
site_author: L Ma
site_description: "timE sERIes pLaYground (EERILY) is a playground for time series"
site_url: "https://emptymalei.github.io/eerily"
repo_url: "https://github.com/emptymalei/eerily"
edit_uri: "blob/main/docs/"
repo_name: "emptymalei/eerily"


theme:
  name: "material"
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/logo.png
  logo: assets/logo_transparent.png



markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: "¤"

plugins:
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: sphinx
      watch:
        - docs

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "Home": index.md
  - References:
    - "Introduction": references/index.md
    - "Data":
      - "data.generators":
        - references/data/generators/index.md
        - "data.generators.stepper": references/data/generators/stepper.md
        - "data.generators.elasticity": references/data/generators/elasticity.md
        - "data.generators.brownian": references/data/generators/brownian.md
  - "Changelog": changelog.md
